import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const achievements = [
  // WATER MONITORING (15 достижений)
  {
    id: 'water_first_sample',
    name: 'Первая проба',
    description: 'Взять первую пробу воды',
    category: 'WATER_MONITORING',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'droplet',
    color: 'from-blue-400 to-cyan-400',
    xpReward: 50,
    orbReward: 10,
    hasNFTBadge: true,
    condition: { type: 'data_count', value: 1, description: 'Добавьте 1 пробу воды' },
    visualDescription: 'Бронзовая медаль с изображением капли воды',
    animationType: 'bubble',
    collectionValue: 1,
  },
  {
    id: 'water_10_samples',
    name: 'Начинающий исследователь',
    description: 'Взять 10 проб воды',
    category: 'WATER_MONITORING',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'droplet',
    color: 'from-blue-400 to-cyan-400',
    xpReward: 150,
    orbReward: 25,
    hasNFTBadge: true,
    condition: { type: 'data_count', value: 10, description: 'Добавьте 10 проб воды' },
    visualDescription: 'Бронзовая медаль с 10 маленькими каплями',
    animationType: 'bubble',
    collectionValue: 2,
  },
  {
    id: 'water_50_samples',
    name: 'Water Guardian',
    description: 'Взять 50 проб воды',
    category: 'WATER_MONITORING',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'shield',
    color: 'from-blue-500 to-cyan-500',
    xpReward: 500,
    orbReward: 100,
    hasNFTBadge: true,
    condition: { type: 'data_count', value: 50, description: 'Добавьте 50 проб воды' },
    visualDescription: 'Серебряный щит с голубой каплей в центре',
    animationType: 'shield',
    collectionValue: 5,
  },
  {
    id: 'water_100_samples',
    name: 'Мастер мониторинга',
    description: 'Взять 100 проб воды',
    category: 'WATER_MONITORING',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'droplets',
    color: 'from-cyan-500 to-blue-500',
    xpReward: 1000,
    orbReward: 200,
    hasNFTBadge: true,
    condition: { type: 'data_count', value: 100, description: 'Добавьте 100 проб воды' },
    visualDescription: 'Серебряная медаль с множеством переплетающихся капель',
    animationType: 'waves',
    collectionValue: 8,
  },
  {
    id: 'water_500_samples',
    name: 'Легенда вод',
    description: 'Взять 500 проб воды',
    category: 'WATER_MONITORING',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'crown',
    color: 'from-blue-600 to-cyan-600',
    xpReward: 5000,
    orbReward: 1000,
    hasNFTBadge: true,
    condition: { type: 'data_count', value: 500, description: 'Добавьте 500 проб воды' },
    visualDescription: 'Золотая корона над волнами',
    animationType: 'crown',
    collectionValue: 20,
  },
  {
    id: 'water_1000_samples',
    name: 'Хранитель океана',
    description: 'Взять 1000 проб воды',
    category: 'WATER_MONITORING',
    rarity: 'LEGENDARY',
    nftMetal: 'PLATINUM',
    icon: 'globe',
    color: 'from-blue-700 to-cyan-700',
    xpReward: 15000,
    orbReward: 5000,
    hasNFTBadge: true,
    condition: { type: 'data_count', value: 1000, description: 'Добавьте 1000 проб воды' },
    visualDescription: 'Платиновый глобус с водной поверхностью',
    animationType: 'globe',
    collectionValue: 50,
  },
  {
    id: 'water_first_object',
    name: 'Первооткрыватель',
    description: 'Добавить первый водный объект на карту',
    category: 'WATER_MONITORING',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'map-pin',
    color: 'from-blue-400 to-cyan-400',
    xpReward: 100,
    orbReward: 20,
    hasNFTBadge: true,
    condition: { type: 'objects_count', value: 1, description: 'Добавьте 1 водный объект' },
    visualDescription: 'Бронзовый маркер карты с каплей',
    animationType: 'pin',
    collectionValue: 2,
  },
  {
    id: 'water_25_objects',
    name: 'Картограф',
    description: 'Добавить 25 водных объектов',
    category: 'WATER_MONITORING',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'map',
    color: 'from-blue-500 to-cyan-500',
    xpReward: 750,
    orbReward: 150,
    hasNFTBadge: true,
    condition: { type: 'objects_count', value: 25, description: 'Добавьте 25 водных объектов' },
    visualDescription: 'Серебряная карта с отмеченными точками',
    animationType: 'map',
    collectionValue: 6,
  },
  {
    id: 'water_quality_expert',
    name: 'Эксперт качества',
    description: 'Провести 100 проверок качества воды',
    category: 'WATER_MONITORING',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'microscope',
    color: 'from-emerald-500 to-teal-500',
    xpReward: 3000,
    orbReward: 600,
    hasNFTBadge: true,
    condition: { type: 'quality_checks', value: 100, description: 'Проведите 100 проверок качества' },
    visualDescription: 'Золотой микроскоп с пробиркой',
    animationType: 'scan',
    collectionValue: 15,
  },
  {
    id: 'water_ph_master',
    name: 'pH Мастер',
    description: 'Измерить pH 50 раз',
    category: 'WATER_MONITORING',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'flask',
    color: 'from-purple-500 to-pink-500',
    xpReward: 400,
    orbReward: 80,
    hasNFTBadge: true,
    condition: { type: 'ph_measurements', value: 50, description: 'Измерьте pH 50 раз' },
    visualDescription: 'Серебряная колба с цветной жидкостью',
    animationType: 'bubble',
    collectionValue: 4,
  },
  {
    id: 'water_turbidity_pro',
    name: 'Специалист по мутности',
    description: 'Измерить мутность 25 раз',
    category: 'WATER_MONITORING',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'eye',
    color: 'from-slate-400 to-gray-400',
    xpReward: 200,
    orbReward: 40,
    hasNFTBadge: true,
    condition: { type: 'turbidity_measurements', value: 25, description: 'Измерьте мутность 25 раз' },
    visualDescription: 'Бронзовый глаз с водяным эффектом',
    animationType: 'pulse',
    collectionValue: 3,
  },
  {
    id: 'water_oxygen_guardian',
    name: 'Защитник кислорода',
    description: 'Измерить растворённый кислород 30 раз',
    category: 'WATER_MONITORING',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'wind',
    color: 'from-sky-400 to-blue-400',
    xpReward: 450,
    orbReward: 90,
    hasNFTBadge: true,
    condition: { type: 'oxygen_measurements', value: 30, description: 'Измерьте кислород 30 раз' },
    visualDescription: 'Серебряные волны с пузырьками',
    animationType: 'bubble',
    collectionValue: 5,
  },
  {
    id: 'water_nitrate_detector',
    name: 'Детектор нитратов',
    description: 'Измерить нитраты 20 раз',
    category: 'WATER_MONITORING',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'test-tube',
    color: 'from-red-400 to-pink-400',
    xpReward: 180,
    orbReward: 35,
    hasNFTBadge: true,
    condition: { type: 'nitrate_measurements', value: 20, description: 'Измерьте нитраты 20 раз' },
    visualDescription: 'Бронзовая пробирка с красной жидкостью',
    animationType: 'bubble',
    collectionValue: 2,
  },
  {
    id: 'water_daily_streak_7',
    name: 'Недельный стрик',
    description: 'Добавлять данные 7 дней подряд',
    category: 'WATER_MONITORING',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'calendar',
    color: 'from-orange-400 to-amber-400',
    xpReward: 350,
    orbReward: 70,
    hasNFTBadge: true,
    condition: { type: 'daily_streak', value: 7, description: '7 дней подряд' },
    visualDescription: 'Серебряный календарь с каплями',
    animationType: 'flip',
    collectionValue: 4,
  },
  {
    id: 'water_daily_streak_30',
    name: 'Месячный стрик',
    description: 'Добавлять данные 30 дней подряд',
    category: 'WATER_MONITORING',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'flame',
    color: 'from-red-500 to-orange-500',
    xpReward: 2000,
    orbReward: 400,
    hasNFTBadge: true,
    condition: { type: 'daily_streak', value: 30, description: '30 дней подряд' },
    visualDescription: 'Золотое пламя с водным эффектом',
    animationType: 'fire',
    collectionValue: 12,
  },

  // SOCIAL (10 достижений)
  {
    id: 'social_first_post',
    name: 'Первый пост',
    description: 'Опубликовать первый пост',
    category: 'SOCIAL',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'message',
    color: 'from-orange-400 to-amber-400',
    xpReward: 50,
    orbReward: 10,
    hasNFTBadge: true,
    condition: { type: 'posts_count', value: 1, description: 'Опубликуйте 1 пост' },
    visualDescription: 'Бронзовый пузырь сообщения',
    animationType: 'pop',
    collectionValue: 1,
  },
  {
    id: 'social_10_posts',
    name: 'Активный автор',
    description: 'Опубликовать 10 постов',
    category: 'SOCIAL',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'edit',
    color: 'from-orange-400 to-amber-400',
    xpReward: 200,
    orbReward: 40,
    hasNFTBadge: true,
    condition: { type: 'posts_count', value: 10, description: 'Опубликуйте 10 постов' },
    visualDescription: 'Бронзовое перо с искрами',
    animationType: 'write',
    collectionValue: 3,
  },
  {
    id: 'social_100_likes',
    name: 'Любимчик',
    description: 'Получить 100 лайков',
    category: 'SOCIAL',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'heart',
    color: 'from-pink-400 to-rose-400',
    xpReward: 150,
    orbReward: 30,
    hasNFTBadge: true,
    condition: { type: 'likes_received', value: 100, description: 'Получите 100 лайков' },
    visualDescription: 'Бронзовое сердце с сиянием',
    animationType: 'heartbeat',
    collectionValue: 2,
  },
  {
    id: 'social_1000_likes',
    name: 'Social Star',
    description: 'Получить 1000 лайков',
    category: 'SOCIAL',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'star',
    color: 'from-yellow-400 to-amber-400',
    xpReward: 1000,
    orbReward: 200,
    hasNFTBadge: true,
    condition: { type: 'likes_received', value: 1000, description: 'Получите 1000 лайков' },
    visualDescription: 'Серебряная звезда с лучами',
    animationType: 'twinkle',
    collectionValue: 8,
  },
  {
    id: 'social_100_followers',
    name: 'Популярный',
    description: 'Набрать 100 подписчиков',
    category: 'SOCIAL',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'users',
    color: 'from-blue-400 to-purple-400',
    xpReward: 500,
    orbReward: 100,
    hasNFTBadge: true,
    condition: { type: 'followers_count', value: 100, description: 'Наберите 100 подписчиков' },
    visualDescription: 'Серебряная группа силуэтов',
    animationType: 'gather',
    collectionValue: 6,
  },
  {
    id: 'social_500_followers',
    name: 'Лидер мнений',
    description: 'Набрать 500 подписчиков',
    category: 'SOCIAL',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'megaphone',
    color: 'from-purple-500 to-pink-500',
    xpReward: 2500,
    orbReward: 500,
    hasNFTBadge: true,
    condition: { type: 'followers_count', value: 500, description: 'Наберите 500 подписчиков' },
    visualDescription: 'Золотой мегафон с волнами',
    animationType: 'broadcast',
    collectionValue: 15,
  },
  {
    id: 'social_first_comment',
    name: 'Комментатор',
    description: 'Написать первый комментарий',
    category: 'SOCIAL',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'message-circle',
    color: 'from-green-400 to-emerald-400',
    xpReward: 30,
    orbReward: 5,
    hasNFTBadge: true,
    condition: { type: 'comments_count', value: 1, description: 'Напишите 1 комментарий' },
    visualDescription: 'Бронзовый пузырь комментария',
    animationType: 'pop',
    collectionValue: 1,
  },
  {
    id: 'social_100_comments',
    name: 'Оратор',
    description: 'Написать 100 комментариев',
    category: 'SOCIAL',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'message-square',
    color: 'from-emerald-400 to-teal-400',
    xpReward: 400,
    orbReward: 80,
    hasNFTBadge: true,
    condition: { type: 'comments_count', value: 100, description: 'Напишите 100 комментариев' },
    visualDescription: 'Серебряный свиток с текстом',
    animationType: 'scroll',
    collectionValue: 5,
  },
  {
    id: 'social_share_master',
    name: 'Шер-мастер',
    description: 'Поделиться 50 постами',
    category: 'SOCIAL',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'share',
    color: 'from-cyan-400 to-blue-400',
    xpReward: 120,
    orbReward: 25,
    hasNFTBadge: true,
    condition: { type: 'shares_count', value: 50, description: 'Поделитесь 50 постами' },
    visualDescription: 'Бронзовая стрелка',
    animationType: 'fly',
    collectionValue: 2,
  },
  {
    id: 'social_community_hero',
    name: 'Герой сообщества',
    description: 'Получить 10000 лайков',
    category: 'SOCIAL',
    rarity: 'LEGENDARY',
    nftMetal: 'PLATINUM',
    icon: 'trophy',
    color: 'from-amber-400 to-yellow-400',
    xpReward: 10000,
    orbReward: 2000,
    hasNFTBadge: true,
    condition: { type: 'likes_received', value: 10000, description: 'Получите 10000 лайков' },
    visualDescription: 'Платиновый трофей с крыльями',
    animationType: 'ascend',
    collectionValue: 40,
  },

  // PROJECT (15 достижений)
  {
    id: 'project_first_contribution',
    name: 'Первый вклад',
    description: 'Внести первый вклад в проект',
    category: 'PROJECT',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'coins',
    color: 'from-purple-400 to-pink-400',
    xpReward: 100,
    orbReward: 20,
    hasNFTBadge: true,
    condition: { type: 'project_contributions', value: 1, description: 'Внесите вклад в 1 проект' },
    visualDescription: 'Бронзовые монеты',
    animationType: 'coin',
    collectionValue: 2,
  },
  {
    id: 'project_investor_100',
    name: 'Инвестор',
    description: 'Инвестировать $100 в проекты',
    category: 'PROJECT',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'trending-up',
    color: 'from-green-400 to-emerald-400',
    xpReward: 200,
    orbReward: 40,
    hasNFTBadge: true,
    condition: { type: 'investment_amount', value: 100, description: 'Инвестируйте $100' },
    visualDescription: 'Бронзовый график роста',
    animationType: 'rise',
    collectionValue: 3,
  },
  {
    id: 'project_investor_1000',
    name: 'Крупный инвестор',
    description: 'Инвестировать $1,000 в проекты',
    category: 'PROJECT',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'wallet',
    color: 'from-emerald-500 to-teal-500',
    xpReward: 1000,
    orbReward: 200,
    hasNFTBadge: true,
    condition: { type: 'investment_amount', value: 1000, description: 'Инвестируйте $1,000' },
    visualDescription: 'Серебряный кошелёк с монетами',
    animationType: 'fill',
    collectionValue: 8,
  },
  {
    id: 'project_investor_10000',
    name: 'Investor Pro',
    description: 'Инвестировать $10,000 в проекты',
    category: 'PROJECT',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'crown',
    color: 'from-amber-500 to-yellow-500',
    xpReward: 5000,
    orbReward: 1000,
    hasNFTBadge: true,
    condition: { type: 'investment_amount', value: 10000, description: 'Инвестируйте $10,000' },
    visualDescription: 'Золотая корона инвестора',
    animationType: 'crown',
    collectionValue: 20,
  },
  {
    id: 'project_first_mission',
    name: 'Миссионер',
    description: 'Выполнить первую миссию',
    category: 'PROJECT',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'target',
    color: 'from-red-400 to-orange-400',
    xpReward: 80,
    orbReward: 15,
    hasNFTBadge: true,
    condition: { type: 'missions_completed', value: 1, description: 'Выполните 1 миссию' },
    visualDescription: 'Бронзовая мишень',
    animationType: 'hit',
    collectionValue: 1,
  },
  {
    id: 'project_10_missions',
    name: 'Активный участник',
    description: 'Выполнить 10 миссий',
    category: 'PROJECT',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'check-circle',
    color: 'from-blue-400 to-cyan-400',
    xpReward: 300,
    orbReward: 60,
    hasNFTBadge: true,
    condition: { type: 'missions_completed', value: 10, description: 'Выполните 10 миссий' },
    visualDescription: 'Бронзовый список с галочками',
    animationType: 'check',
    collectionValue: 4,
  },
  {
    id: 'project_100_missions',
    name: 'Mission Master',
    description: 'Выполнить 100 миссий',
    category: 'PROJECT',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'award',
    color: 'from-purple-500 to-pink-500',
    xpReward: 5000,
    orbReward: 1000,
    hasNFTBadge: true,
    condition: { type: 'missions_completed', value: 100, description: 'Выполните 100 миссий' },
    visualDescription: 'Золотая медаль с лавровым венком',
    animationType: 'rotate',
    collectionValue: 20,
  },
  {
    id: 'project_creator',
    name: 'Создатель',
    description: 'Создать первый проект',
    category: 'PROJECT',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'plus-circle',
    color: 'from-indigo-400 to-purple-400',
    xpReward: 500,
    orbReward: 100,
    hasNFTBadge: true,
    condition: { type: 'projects_created', value: 1, description: 'Создайте 1 проект' },
    visualDescription: 'Серебряный круг с плюсом',
    animationType: 'expand',
    collectionValue: 6,
  },
  {
    id: 'project_5_projects',
    name: 'Предприниматель',
    description: 'Создать 5 проектов',
    category: 'PROJECT',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'briefcase',
    color: 'from-slate-400 to-gray-400',
    xpReward: 1500,
    orbReward: 300,
    hasNFTBadge: true,
    condition: { type: 'projects_created', value: 5, description: 'Создайте 5 проектов' },
    visualDescription: 'Серебряный портфель',
    animationType: 'open',
    collectionValue: 10,
  },
  {
    id: 'project_funded',
    name: 'Успешный сбор',
    description: 'Полностью финансировать проект',
    category: 'PROJECT',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'rocket',
    color: 'from-orange-400 to-red-400',
    xpReward: 1000,
    orbReward: 200,
    hasNFTBadge: true,
    condition: { type: 'projects_funded', value: 1, description: 'Финансируйте 1 проект' },
    visualDescription: 'Серебряная ракета',
    animationType: 'launch',
    collectionValue: 8,
  },
  {
    id: 'project_volunteer',
    name: 'Волонтёр',
    description: 'Участвовать в 10 проектах',
    category: 'PROJECT',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'hand',
    color: 'from-green-400 to-teal-400',
    xpReward: 250,
    orbReward: 50,
    hasNFTBadge: true,
    condition: { type: 'projects_joined', value: 10, description: 'Присоединитесь к 10 проектам' },
    visualDescription: 'Бронзовая рука помощи',
    animationType: 'wave',
    collectionValue: 3,
  },
  {
    id: 'project_mentor',
    name: 'Ментор',
    description: 'Быть лидером в 5 проектах',
    category: 'PROJECT',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'graduation-cap',
    color: 'from-indigo-500 to-purple-500',
    xpReward: 2000,
    orbReward: 400,
    hasNFTBadge: true,
    condition: { type: 'projects_as_lead', value: 5, description: 'Будьте лидером в 5 проектах' },
    visualDescription: 'Золотая академическая шапочка',
    animationType: 'glow',
    collectionValue: 12,
  },
  {
    id: 'project_milestone',
    name: 'Достижение цели',
    description: 'Завершить 25 этапов проекта',
    category: 'PROJECT',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'flag',
    color: 'from-red-400 to-pink-400',
    xpReward: 750,
    orbReward: 150,
    hasNFTBadge: true,
    condition: { type: 'milestones_completed', value: 25, description: 'Завершите 25 этапов' },
    visualDescription: 'Серебряный флаг на вершине',
    animationType: 'plant',
    collectionValue: 6,
  },
  {
    id: 'project_impact',
    name: 'Влияние',
    description: 'Повлиять на 1000 человек через проекты',
    category: 'PROJECT',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'globe',
    color: 'from-blue-500 to-green-500',
    xpReward: 3000,
    orbReward: 600,
    hasNFTBadge: true,
    condition: { type: 'people_impacted', value: 1000, description: 'Повлияйте на 1000 человек' },
    visualDescription: 'Золотой глобус с лучами',
    animationType: 'pulse',
    collectionValue: 15,
  },
  {
    id: 'project_legend',
    name: 'Легенда проектов',
    description: 'Достичь общего влияния $100,000',
    category: 'PROJECT',
    rarity: 'LEGENDARY',
    nftMetal: 'PLATINUM',
    icon: 'star',
    color: 'from-amber-400 to-yellow-400',
    xpReward: 15000,
    orbReward: 5000,
    hasNFTBadge: true,
    condition: { type: 'total_impact', value: 100000, description: 'Влияние $100,000' },
    visualDescription: 'Платиновая звезда с ореолом',
    animationType: 'supernova',
    collectionValue: 50,
  },

  // RESEARCH (10 достижений)
  {
    id: 'research_first_validation',
    name: 'Первая валидация',
    description: 'Валидировать первую исследовательскую работу',
    category: 'RESEARCH',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'check',
    color: 'from-emerald-400 to-green-400',
    xpReward: 100,
    orbReward: 20,
    hasNFTBadge: true,
    condition: { type: 'validations_count', value: 1, description: 'Валидируйте 1 работу' },
    visualDescription: 'Бронзовая галочка',
    animationType: 'check',
    collectionValue: 2,
  },
  {
    id: 'research_10_validations',
    name: 'Рецензент',
    description: 'Валидировать 10 исследований',
    category: 'RESEARCH',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'file-check',
    color: 'from-emerald-400 to-teal-400',
    xpReward: 300,
    orbReward: 60,
    hasNFTBadge: true,
    condition: { type: 'validations_count', value: 10, description: 'Валидируйте 10 исследований' },
    visualDescription: 'Бронзовый документ с печатью',
    animationType: 'stamp',
    collectionValue: 4,
  },
  {
    id: 'research_100_validations',
    name: 'Scientist',
    description: 'Валидировать 100 исследований',
    category: 'RESEARCH',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'flask-conical',
    color: 'from-teal-400 to-cyan-400',
    xpReward: 1500,
    orbReward: 300,
    hasNFTBadge: true,
    condition: { type: 'validations_count', value: 100, description: 'Валидируйте 100 исследований' },
    visualDescription: 'Серебряная колба с bubbling жидкостью',
    animationType: 'bubble',
    collectionValue: 10,
  },
  {
    id: 'research_first_paper',
    name: 'Автор',
    description: 'Опубликовать первую научную работу',
    category: 'RESEARCH',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'file-text',
    color: 'from-blue-400 to-indigo-400',
    xpReward: 500,
    orbReward: 100,
    hasNFTBadge: true,
    condition: { type: 'papers_published', value: 1, description: 'Опубликуйте 1 работу' },
    visualDescription: 'Серебряный свиток',
    animationType: 'unroll',
    collectionValue: 6,
  },
  {
    id: 'research_10_papers',
    name: 'Плодовитый учёный',
    description: 'Опубликовать 10 научных работ',
    category: 'RESEARCH',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'library',
    color: 'from-indigo-500 to-purple-500',
    xpReward: 3000,
    orbReward: 600,
    hasNFTBadge: true,
    condition: { type: 'papers_published', value: 10, description: 'Опубликуйте 10 работ' },
    visualDescription: 'Золотая библиотека',
    animationType: 'stack',
    collectionValue: 15,
  },
  {
    id: 'research_citations_100',
    name: 'Цитируемый',
    description: 'Получить 100 цитирований',
    category: 'RESEARCH',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'quote',
    color: 'from-violet-400 to-purple-400',
    xpReward: 800,
    orbReward: 160,
    hasNFTBadge: true,
    condition: { type: 'citations_count', value: 100, description: 'Получите 100 цитирований' },
    visualDescription: 'Серебряные кавычки',
    animationType: 'float',
    collectionValue: 7,
  },
  {
    id: 'research_citations_1000',
    name: 'Влиятельный учёный',
    description: 'Получить 1000 цитирований',
    category: 'RESEARCH',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'trending-up',
    color: 'from-purple-500 to-pink-500',
    xpReward: 5000,
    orbReward: 1000,
    hasNFTBadge: true,
    condition: { type: 'citations_count', value: 1000, description: 'Получите 1000 цитирований' },
    visualDescription: 'Золотой график цитирований',
    animationType: 'rise',
    collectionValue: 20,
  },
  {
    id: 'research_grant',
    name: 'Грантополучатель',
    description: 'Получить первый грант',
    category: 'RESEARCH',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'award',
    color: 'from-amber-400 to-yellow-400',
    xpReward: 1000,
    orbReward: 200,
    hasNFTBadge: true,
    condition: { type: 'grants_received', value: 1, description: 'Получите 1 грант' },
    visualDescription: 'Серебряная медаль гранта',
    animationType: 'shine',
    collectionValue: 8,
  },
  {
    id: 'research_collaboration',
    name: 'Коллаборатор',
    description: 'Участвовать в 10 совместных исследованиях',
    category: 'RESEARCH',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'users',
    color: 'from-cyan-400 to-blue-400',
    xpReward: 250,
    orbReward: 50,
    hasNFTBadge: true,
    condition: { type: 'collaborations_count', value: 10, description: '10 совместных исследований' },
    visualDescription: 'Бронзовые соединённые фигуры',
    animationType: 'connect',
    collectionValue: 3,
  },
  {
    id: 'research_breakthrough',
    name: 'Прорыв',
    description: 'Опубликовать прорывное исследование',
    category: 'RESEARCH',
    rarity: 'LEGENDARY',
    nftMetal: 'PLATINUM',
    icon: 'lightbulb',
    color: 'from-yellow-400 to-amber-400',
    xpReward: 10000,
    orbReward: 2000,
    hasNFTBadge: true,
    condition: { type: 'breakthrough_papers', value: 1, description: '1 прорывная работа' },
    visualDescription: 'Платиновая лампочка с лучами',
    animationType: 'flash',
    collectionValue: 40,
  },

  // EDUCATION (10 достижений)
  {
    id: 'education_first_course',
    name: 'Первый курс',
    description: 'Завершить первый образовательный курс',
    category: 'EDUCATION',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'book',
    color: 'from-yellow-400 to-amber-400',
    xpReward: 100,
    orbReward: 20,
    hasNFTBadge: true,
    condition: { type: 'courses_completed', value: 1, description: 'Завершите 1 курс' },
    visualDescription: 'Бронзовая книга',
    animationType: 'open',
    collectionValue: 2,
  },
  {
    id: 'education_5_courses',
    name: 'Студент',
    description: 'Завершить 5 курсов',
    category: 'EDUCATION',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'books',
    color: 'from-amber-400 to-orange-400',
    xpReward: 300,
    orbReward: 60,
    hasNFTBadge: true,
    condition: { type: 'courses_completed', value: 5, description: 'Завершите 5 курсов' },
    visualDescription: 'Бронзовая стопка книг',
    animationType: 'stack',
    collectionValue: 4,
  },
  {
    id: 'education_20_courses',
    name: 'Учёный',
    description: 'Завершить 20 курсов',
    category: 'EDUCATION',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'graduation-cap',
    color: 'from-indigo-400 to-purple-400',
    xpReward: 1000,
    orbReward: 200,
    hasNFTBadge: true,
    condition: { type: 'courses_completed', value: 20, description: 'Завершите 20 курсов' },
    visualDescription: 'Серебряная академическая шапочка',
    animationType: 'toss',
    collectionValue: 8,
  },
  {
    id: 'education_perfect_score',
    name: 'Отличник',
    description: 'Получить 100% за курс',
    category: 'EDUCATION',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'star',
    color: 'from-yellow-400 to-amber-400',
    xpReward: 500,
    orbReward: 100,
    hasNFTBadge: true,
    condition: { type: 'perfect_scores', value: 1, description: '1 курс на 100%' },
    visualDescription: 'Серебряная звезда с блеском',
    animationType: 'twinkle',
    collectionValue: 6,
  },
  {
    id: 'education_quiz_master',
    name: 'Мастер тестов',
    description: 'Правильно ответить на 100 вопросов',
    category: 'EDUCATION',
    rarity: 'COMMON',
    nftMetal: 'BRONZE',
    icon: 'circle-help',
    color: 'from-green-400 to-emerald-400',
    xpReward: 200,
    orbReward: 40,
    hasNFTBadge: true,
    condition: { type: 'quiz_correct', value: 100, description: '100 правильных ответов' },
    visualDescription: 'Бронзовый график с галочкой',
    animationType: 'rise',
    collectionValue: 3,
  },
  {
    id: 'education_mentor',
    name: 'Наставник',
    description: 'Помочь 50 студентам',
    category: 'EDUCATION',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'heart-handshake',
    color: 'from-pink-400 to-rose-400',
    xpReward: 750,
    orbReward: 150,
    hasNFTBadge: true,
    condition: { type: 'students_helped', value: 50, description: 'Помогите 50 студентам' },
    visualDescription: 'Серебряные рукопожатие',
    animationType: 'shake',
    collectionValue: 7,
  },
  {
    id: 'education_content_creator',
    name: 'Создатель контента',
    description: 'Создать 10 учебных материалов',
    category: 'EDUCATION',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'pen-tool',
    color: 'from-blue-500 to-indigo-500',
    xpReward: 2000,
    orbReward: 400,
    hasNFTBadge: true,
    condition: { type: 'materials_created', value: 10, description: 'Создайте 10 материалов' },
    visualDescription: 'Золотое перо',
    animationType: 'write',
    collectionValue: 12,
  },
  {
    id: 'education_teacher',
    name: 'Преподаватель',
    description: 'Провести 20 уроков',
    category: 'EDUCATION',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'chalkboard',
    color: 'from-slate-500 to-gray-500',
    xpReward: 2500,
    orbReward: 500,
    hasNFTBadge: true,
    condition: { type: 'lessons_taught', value: 20, description: 'Проведите 20 уроков' },
    visualDescription: 'Золотая доска',
    animationType: 'draw',
    collectionValue: 15,
  },
  {
    id: 'education_phd',
    name: 'Доктор наук',
    description: 'Завершить все курсы в категории',
    category: 'EDUCATION',
    rarity: 'LEGENDARY',
    nftMetal: 'PLATINUM',
    icon: 'scroll',
    color: 'from-purple-500 to-pink-500',
    xpReward: 10000,
    orbReward: 2000,
    hasNFTBadge: true,
    condition: { type: 'category_complete', value: 1, description: 'Завершите категорию' },
    visualDescription: 'Платиновый диплом',
    animationType: 'unroll',
    collectionValue: 40,
  },
  {
    id: 'education_lifelong',
    name: 'Вечный студент',
    description: 'Учиться 365 дней подряд',
    category: 'EDUCATION',
    rarity: 'LEGENDARY',
    nftMetal: 'PLATINUM',
    icon: 'infinity',
    color: 'from-cyan-400 to-blue-400',
    xpReward: 15000,
    orbReward: 5000,
    hasNFTBadge: true,
    condition: { type: 'learning_streak', value: 365, description: '365 дней обучения' },
    visualDescription: 'Платиновый знак бесконечности',
    animationType: 'loop',
    collectionValue: 50,
  },

  // SPECIAL (10 достижений)
  {
    id: 'special_early_adopter',
    name: 'Early Adopter',
    description: 'Войти в первые 1000 пользователей',
    category: 'SPECIAL',
    rarity: 'LEGENDARY',
    nftMetal: 'PLATINUM',
    icon: 'rocket',
    color: 'from-blue-400 to-purple-400',
    xpReward: 5000,
    orbReward: 1000,
    hasNFTBadge: true,
    condition: { type: 'early_user', value: 1000, description: 'Первые 1000 пользователей' },
    visualDescription: 'Платиновая ракета со звёздами',
    animationType: 'launch',
    collectionValue: 30,
  },
  {
    id: 'special_founder',
    name: 'Основатель',
    description: 'Быть среди первых 100 пользователей',
    category: 'SPECIAL',
    rarity: 'LEGENDARY',
    nftMetal: 'PLATINUM',
    icon: 'crown',
    color: 'from-amber-400 to-yellow-400',
    xpReward: 10000,
    orbReward: 2000,
    hasNFTBadge: true,
    condition: { type: 'founder_user', value: 100, description: 'Первые 100 пользователей' },
    visualDescription: 'Платиновая корона основателя',
    animationType: 'crown',
    collectionValue: 50,
  },
  {
    id: 'special_referral_master',
    name: 'Реферальный мастер',
    description: 'Пригласить 50 друзей',
    category: 'SPECIAL',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'users',
    color: 'from-green-400 to-emerald-400',
    xpReward: 2500,
    orbReward: 500,
    hasNFTBadge: true,
    condition: { type: 'referrals_count', value: 50, description: 'Пригласите 50 друзей' },
    visualDescription: 'Золотое дерево рефералов',
    animationType: 'grow',
    collectionValue: 15,
  },
  {
    id: 'special_whale',
    name: 'Кит',
    description: 'Иметь баланс 100,000 ORB',
    category: 'SPECIAL',
    rarity: 'LEGENDARY',
    nftMetal: 'PLATINUM',
    icon: 'wallet',
    color: 'from-cyan-400 to-blue-400',
    xpReward: 10000,
    orbReward: 2000,
    hasNFTBadge: true,
    condition: { type: 'balance_threshold', value: 100000, description: 'Баланс 100,000 ORB' },
    visualDescription: 'Платиновый кошелёк с монетами',
    animationType: 'fill',
    collectionValue: 40,
  },
  {
    id: 'special_marathon',
    name: 'Марафонец',
    description: 'Быть активным 100 дней',
    category: 'SPECIAL',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'calendar',
    color: 'from-orange-400 to-red-400',
    xpReward: 3000,
    orbReward: 600,
    hasNFTBadge: true,
    condition: { type: 'active_days', value: 100, description: '100 активных дней' },
    visualDescription: 'Золотой календарь с отметками',
    animationType: 'flip',
    collectionValue: 15,
  },
  {
    id: 'special_bug_hunter',
    name: 'Охотник за багами',
    description: 'Найти и сообщить о 10 багах',
    category: 'SPECIAL',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'bug',
    color: 'from-red-400 to-pink-400',
    xpReward: 1000,
    orbReward: 200,
    hasNFTBadge: true,
    condition: { type: 'bugs_reported', value: 10, description: 'Сообщите о 10 багах' },
    visualDescription: 'Серебряный жук с лупой',
    animationType: 'scan',
    collectionValue: 8,
  },
  {
    id: 'special_translator',
    name: 'Переводчик',
    description: 'Перевести 10000 слов',
    category: 'SPECIAL',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'languages',
    color: 'from-blue-400 to-indigo-400',
    xpReward: 800,
    orbReward: 160,
    hasNFTBadge: true,
    condition: { type: 'words_translated', value: 10000, description: 'Переведите 10000 слов' },
    visualDescription: 'Серебряный глобус с текстом',
    animationType: 'rotate',
    collectionValue: 7,
  },
  {
    id: 'special_event_winner',
    name: 'Победитель события',
    description: 'Выиграть специальное событие',
    category: 'SPECIAL',
    rarity: 'EPIC',
    nftMetal: 'GOLD',
    icon: 'trophy',
    color: 'from-amber-400 to-yellow-400',
    xpReward: 5000,
    orbReward: 1000,
    hasNFTBadge: true,
    condition: { type: 'events_won', value: 1, description: 'Выиграйте 1 событие' },
    visualDescription: 'Золотой кубок',
    animationType: 'lift',
    collectionValue: 20,
  },
  {
    id: 'special_dao_participant',
    name: 'Участник DAO',
    description: 'Проголосовать в 50 голосованиях DAO',
    category: 'SPECIAL',
    rarity: 'RARE',
    nftMetal: 'SILVER',
    icon: 'vote',
    color: 'from-purple-400 to-pink-400',
    xpReward: 750,
    orbReward: 150,
    hasNFTBadge: true,
    condition: { type: 'dao_votes', value: 50, description: '50 голосований DAO' },
    visualDescription: 'Серебрярный ballot box',
    animationType: 'check',
    collectionValue: 7,
  },
  {
    id: 'special_legend',
    name: 'Легенда LoopOrb',
    description: 'Получить все остальные достижения',
    category: 'SPECIAL',
    rarity: 'LEGENDARY',
    nftMetal: 'PLATINUM',
    icon: 'sparkles',
    color: 'from-pink-400 via-purple-400 to-cyan-400',
    xpReward: 50000,
    orbReward: 10000,
    hasNFTBadge: true,
    condition: { type: 'all_achievements', value: 1, description: 'Все достижения' },
    visualDescription: 'Платиновая звезда со всеми символами',
    animationType: 'supernova',
    collectionValue: 100,
  },
];

async function main() {
  console.log('🏆 Seeding achievements...');

  // Delete existing achievements (optional - comment out in production)
  // await prisma.userAchievement.deleteMany();
  // await prisma.achievement.deleteMany();

  // Create achievements
  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { id: achievement.id },
      update: achievement,
      create: achievement,
    });
    console.log(`  ✓ ${achievement.name}`);
  }

  console.log(`✅ Seeded ${achievements.length} achievements`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
